[config]
schemaVersion = "0.0.1"

[package]
# The name of the team you are publishing as
namespace = "ThunderstoreUserName"
# max 250 characters
description = "Example mod description"

# Replace this with a correct repo URL if the default is not accurate
websiteUrl = "https://github.com/UserName/SilksongPlugin__1"
containsNsfwContent = false

# dependencies are specified in the format AuthorName-PackageName = "version". You should always have at least BepInExPack_Silksong.
[package.dependencies]
BepInEx-BepInExPack_Silksong = "5.4.2304"


[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./dist"

[[build.copy]]
source = "./tmp"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "hollow-knight-silksong" ]

[publish.categories]
# available categories can be found at https://github.com/thunderstore-io/ecosystem-schema/blob/master/games/data/hollow-knight-silksong.yml
hollow-knight-silksong = [ "mods" ]
